# Generated by Django 4.0.4 on 2022-06-19 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KBA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 40, 28, 682922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roster',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 40, 28, 682371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='no_titles',
            field=models.IntegerField(help_text='Number of Championship Title'),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 40, 28, 681576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='year_formed',
            field=models.IntegerField(max_length=4),
        ),
    ]
