# Generated by Django 4.0.4 on 2022-06-19 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KBA', '0002_alter_player_updated_alter_roster_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.CharField(blank=True, choices=[('HS', 'High School'), ('COLL', 'College'), ('D1', 'Division 1'), ('INDY', 'Independent League'), ('MILB', 'Minor League'), ('MLB', 'Major League'), ('PRO', 'A Professional League')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='joined',
            field=models.IntegerField(max_length='4'),
        ),
        migrations.AlterField(
            model_name='player',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 45, 5, 587754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roster',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 45, 5, 587193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 7, 45, 5, 586410, tzinfo=utc)),
        ),
    ]
