# Generated by Django 4.0.5 on 2022-06-23 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KBA', '0006_alter_player_updated_alter_roster_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(choices=[('Pitcher', (('P', 'Pitcher'), ('SP', 'Starting Pitcher'), ('RP', 'Relief Pitcher'))), ('Catcher', (('C', 'Catcher'),)), ('Infielder', (('IF', 'Infield'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'))), ('Outfielder', (('OF', 'Outfield'), ('LF', 'Left Field'), ('RF', 'Right Field'), ('CF', 'Center Field'))), ('Utility', (('Util', 'Utility'),))], default=(('IF', 'Infield'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop')), max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 3, 38, 44, 403122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roster',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 3, 38, 44, 402752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 3, 38, 44, 402048, tzinfo=utc)),
        ),
    ]
